<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WebDriver' => array($vendorDir . '/instaclick/php-webdriver/lib'),
    'Stack' => array($vendorDir . '/stack/builder/src'),
    'EasyRdf_' => array($vendorDir . '/easyrdf/easyrdf/lib'),
    'Dflydev\\DotAccessData' => array($vendorDir . '/dflydev/dot-access-data/src'),
    'Dflydev\\DotAccessConfiguration' => array($vendorDir . '/dflydev/dot-access-configuration/src'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
);
