<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'zaporylie\\ComposerDrupalOptimizations\\' => array($vendorDir . '/zaporylie/composer-drupal-optimizations/src'),
    'cweagans\\Composer\\' => array($vendorDir . '/cweagans/composer-patches/src'),
    'Zumba\\Mink\\Driver\\' => array($vendorDir . '/jcalderonzumba/mink-phantomjs-driver/src'),
    'Zumba\\GastonJS\\' => array($vendorDir . '/jcalderonzumba/gastonjs/src'),
    'Webmozart\\PathUtil\\' => array($vendorDir . '/webmozart/path-util/src'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Cmf\\Component\\Routing\\' => array($vendorDir . '/symfony-cmf/routing'),
    'Symfony\\Bridge\\PsrHttpMessage\\' => array($vendorDir . '/symfony/psr-http-message-bridge'),
    'Stecman\\Component\\Symfony\\Console\\BashCompletion\\' => array($vendorDir . '/stecman/symfony-console-completion/src'),
    'SelfUpdate\\' => array($vendorDir . '/consolidation/self-update/src'),
    'Seld\\PharUtils\\' => array($vendorDir . '/seld/phar-utils/src'),
    'Seld\\JsonLint\\' => array($vendorDir . '/seld/jsonlint/src/Seld/JsonLint'),
    'Robo\\' => array($vendorDir . '/consolidation/robo/src'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src/PhpOption'),
    'PHPCSStandards\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\' => array($vendorDir . '/dealerdirect/phpcodesniffer-composer-installer/src'),
    'League\\Container\\' => array($vendorDir . '/league/container/src'),
    'Interop\\Container\\' => array($vendorDir . '/container-interop/container-interop/src/Interop/Container'),
    'Grasmash\\YamlExpander\\' => array($vendorDir . '/grasmash/yaml-expander/src'),
    'Grasmash\\Expander\\' => array($vendorDir . '/grasmash/expander/src'),
    'Goutte\\' => array($vendorDir . '/fabpot/goutte/Goutte'),
    'Drush\\Internal\\' => array($vendorDir . '/drush/drush/src/internal-forks'),
    'Drush\\' => array($vendorDir . '/drush/drush/src'),
    'Drupal\\Console\\Composer\\Plugin\\' => array($vendorDir . '/drupal/console-extend-plugin/src'),
    'Drupal\\Composer\\Plugin\\Scaffold\\' => array($vendorDir . '/drupal/core-composer-scaffold'),
    'Drupal\\' => array($vendorDir . '/drupal/coder/coder_sniffer/Drupal'),
    'DrupalPractice\\' => array($vendorDir . '/drupal/coder/coder_sniffer/DrupalPractice'),
    'DrupalCodeGenerator\\' => array($vendorDir . '/chi-teck/drupal-code-generator/src'),
    'Dotenv\\' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Consolidation\\SiteProcess\\' => array($vendorDir . '/consolidation/site-process/src'),
    'Consolidation\\SiteAlias\\' => array($vendorDir . '/consolidation/site-alias/src'),
    'Consolidation\\Log\\' => array($vendorDir . '/consolidation/log/src'),
    'Consolidation\\Filter\\' => array($vendorDir . '/consolidation/filter-via-dot-access-data/src'),
    'Consolidation\\Config\\' => array($vendorDir . '/consolidation/config/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Composer\\' => array($vendorDir . '/composer/composer/src/Composer'),
    'Behat\\Mink\\Driver\\' => array($vendorDir . '/behat/mink-goutte-driver/src', $vendorDir . '/behat/mink-selenium2-driver/src'),
    'Asm89\\Stack\\' => array($vendorDir . '/asm89/stack-cors/src/Asm89/Stack'),
    'Alchemy\\Zippy\\' => array($vendorDir . '/alchemy/zippy/src'),
);
