<?php return array(
    'root' => array(
        'name' => 'drupal-composer/drupal-project',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'alchemy/zippy' => array(
            'pretty_version' => '0.4.9',
            'version' => '0.4.9.0',
            'reference' => '59fbeefb9a249122867ef25e53addfcce31850d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../alchemy/zippy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'asm89/stack-cors' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'b9c31def6a83f84b4d4a40d35996d375755f0e08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'behat/mink' => array(
            'pretty_version' => 'v1.8.1',
            'version' => '1.8.1.0',
            'reference' => '07c6a9fe3fa98c2de074b25d9ed26c22904e3887',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/mink',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'behat/mink-browserkit-driver' => array(
            'pretty_version' => 'v1.3.4',
            'version' => '1.3.4.0',
            'reference' => 'e3b90840022ebcd544c7b394a3c9597ae242cbee',
            'type' => 'mink-driver',
            'install_path' => __DIR__ . '/../behat/mink-browserkit-driver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'behat/mink-goutte-driver' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'reference' => '8b9ad6d2d95bc70b840d15323365f52fcdaea6ca',
            'type' => 'mink-driver',
            'install_path' => __DIR__ . '/../behat/mink-goutte-driver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'behat/mink-selenium2-driver' => array(
            'pretty_version' => 'v1.4.0',
            'version' => '1.4.0.0',
            'reference' => '312a967dd527f28980cce40850339cd5316da092',
            'type' => 'mink-driver',
            'install_path' => __DIR__ . '/../behat/mink-selenium2-driver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'chi-teck/drupal-code-generator' => array(
            'pretty_version' => '1.32.0',
            'version' => '1.32.0.0',
            'reference' => '0e045f7a7e747af3d8f603156bf4d73be5768246',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chi-teck/drupal-code-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codegyre/robo' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '< 1.0',
            ),
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.2.7',
            'version' => '1.2.7.0',
            'reference' => '95c63ab2117a72f48f5a55da9740a3273d45b7fd',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/composer' => array(
            'pretty_version' => '1.10.6',
            'version' => '1.10.6.0',
            'reference' => 'be81b9c4735362c26876bdbfd3b5bc7e7f711c88',
            'type' => 'library',
            'install_path' => __DIR__ . '/./composer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'd20a64ed3c94748397ff5973488761b22f6d3f19',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'reference' => 'c6bea70230ef4dd483e6bbcab6005f682ed3a8de',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/spdx-licenses' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'reference' => '0c3e51e1880ca149682332770e25977c70cf9dae',
            'type' => 'library',
            'install_path' => __DIR__ . '/./spdx-licenses',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '1ab9842d69e64fb3a01be6b656501032d1b78cb7',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'consolidation/annotated-command' => array(
            'pretty_version' => '2.12.0',
            'version' => '2.12.0.0',
            'reference' => '512a2e54c98f3af377589de76c43b24652bcb789',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/annotated-command',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/config' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'cac1279bae7efb5c7fb2ca4c3ba4b8eb741a96c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/filter-via-dot-access-data' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'a53e96c6b9f7f042f5e085bf911f3493cea823c6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/filter-via-dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/log' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'b2e887325ee90abc96b0a8b7b474cd9e7c896e3a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/output-formatters' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'reference' => '99ec998ffb697e0eada5aacf81feebfb13023605',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/output-formatters',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/robo' => array(
            'pretty_version' => '1.4.12',
            'version' => '1.4.12.0',
            'reference' => 'eb45606f498b3426b9a98b7c85e300666a968e51',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/robo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/self-update' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'dba6b2c0708f20fa3ba8008a2353b637578849b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/self-update',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/site-alias' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '8cfd3b6ab6d541086fc970bf850864293b284e6f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-alias',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/site-process' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'f3211fa4c60671c6f068184221f06f932556e443',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'container-interop/container-interop' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '79cbf1341c22ec75643d841642dd5d6acd83bdb8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../container-interop/container-interop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'container-interop/container-interop-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.2',
            ),
        ),
        'cweagans/composer-patches' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => 'e190d4466fe2b103a55467dfa83fc2fecfcaf2db',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../cweagans/composer-patches',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '4be43904336affa5c2f70744a348312336afd0da',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dflydev/dot-access-configuration' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => '2e6eb0c8b8830b26bb23defcfc38d4276508fc49',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-configuration',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'reference' => '3fbd874921ab2c041e899d044585a2ab9795df8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dflydev/placeholder-resolver' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'c498d0cae91b1bb36cc7d60906dab8e62bb7c356',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/placeholder-resolver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.10.2',
            'version' => '1.10.2.0',
            'reference' => 'b9d758e831c70751155c698c2f7df4665314a1cb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'reference' => '382e7f4db9a12dc6c19431743a2b096041bcdd62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '1.6.4',
            'version' => '1.6.4.0',
            'reference' => '6b1e4b2b66f6d6e49983cebfe23a21b7ccc5b0d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'reference' => '308728eae8d90412d850c155d40b1cfbede549da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '629572819973f13486371cb611386eb17851e85c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => '4111f6853aea6f28b2b1dcfdde83d12dd3d5e6e3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'ae466f726242e637cebdd526a7d991b9433bacf1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '5242d66dbeb21a30dd8a3e66bf7a73b66e05e1f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '1.3.7',
            'version' => '1.3.7.0',
            'reference' => '0af483f91bada1c9ded6c2cfd26ab7d5ab2094e0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/reflection' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '55e71912dfcd824b2fdd16f2d9afe15684cfce79',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/reflection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal-composer/drupal-project' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/action' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/admin_toolbar' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '8.x-2.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/admin_toolbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/aggregator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/automated_cron' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/ban' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/bartik' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/basic_auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/better_exposed_filters' => array(
            'pretty_version' => '4.0.0-beta1',
            'version' => '4.0.0.0-beta1',
            'reference' => '8.x-4.0-beta1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/better_exposed_filters',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/big_pipe' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/block' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/block_content' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/block_place' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/book' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/breakpoint' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/ckeditor' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/claro' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/classy' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/coder' => array(
            'pretty_version' => '8.3.9',
            'version' => '8.3.9.0',
            'reference' => 'd51e0b8c6561e21c0545d04b5410a7bed7ee7c6b',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../drupal/coder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'drupal/color' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/comment' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/config_filter' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '8.x-1.5',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/config_filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/config_ignore' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '8.x-2.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/config_ignore',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/config_translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/console' => array(
            'pretty_version' => '1.9.4',
            'version' => '1.9.4.0',
            'reference' => '04522b687b2149dc1f808599e716421a20d50a5b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drupal/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/console-core' => array(
            'pretty_version' => '1.9.4',
            'version' => '1.9.4.0',
            'reference' => 'cc6f50c6ac8199140224347c862df75fd2d2f5ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drupal/console-core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/console-en' => array(
            'pretty_version' => '1.9.4',
            'version' => '1.9.4.0',
            'reference' => '30813a832fdb1244e84cbcc012cd103d5e9d673d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drupal/console-en',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/console-extend-plugin' => array(
            'pretty_version' => '0.9.5',
            'version' => '0.9.5.0',
            'reference' => 'eff6da99cfb5fe1fc60990672d2667c402eb3585',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/console-extend-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/contact' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/content_moderation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/content_translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/contextual' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core' => array(
            'pretty_version' => '8.8.6',
            'version' => '8.8.6.0',
            'reference' => 'a5daf2aa45bbc72da72e1e64d5261f746ffb508c',
            'type' => 'drupal-core',
            'install_path' => __DIR__ . '/../../web/core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-annotation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-assertion' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-bridge' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-class-finder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-composer-scaffold' => array(
            'pretty_version' => '8.9.20',
            'version' => '8.9.20.0',
            'reference' => 'c902d07cb49ef73777e2b33a39e54c2861a8c81d',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-composer-scaffold',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-datetime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-dependency-injection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-dev' => array(
            'pretty_version' => '8.8.6',
            'version' => '8.8.6.0',
            'reference' => 'edeec67c12be4b459d2873ac99044787b51ebe42',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'drupal/core-diff' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-discovery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-event-dispatcher' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-file-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-file-security' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-gettext' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-graph' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-http-foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-php-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-plugin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-proxy-builder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-render' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-serialization' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-transliteration' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/core-version' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/ctools' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => '8.x-3.4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/ctools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/datetime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/datetime_range' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/dblog' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/devel' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '8.x-2.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/devel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/dynamic_page_cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/editor' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/entity_reference' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/entity_reference_revisions' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '8.x-1.8',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/entity_reference_revisions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/field' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/field_group' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '8.x-3.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/field_group',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/field_layout' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/field_ui' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/file' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/filter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/forum' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/hal' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/help' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/help_topics' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/history' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/image' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/inline_form_errors' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/jsonapi' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/language' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/layout_builder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/layout_discovery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/link' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/locale' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/media' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/media_library' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/menu_link_content' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/menu_ui' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/metatag' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'reference' => '8.x-1.13',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/metatag',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/migrate_drupal' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/migrate_drupal_multilingual' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/migrate_drupal_ui' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/minimal' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/node' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/options' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/page_cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/paragraphs' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '8.x-1.11',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/paragraphs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/path' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/path_alias' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/pathauto' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => '8.x-1.8',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/pathauto',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/quickedit' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/rdf' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/responsive_image' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/rest' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/search' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/search_api' => array(
            'pretty_version' => '1.16.0',
            'version' => '1.16.0.0',
            'reference' => '8.x-1.16',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/search_api',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/serialization' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/settings_tray' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/seven' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/shortcut' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/simpletest' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/standard' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/stark' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/statistics' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/syslog' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/system' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/taxonomy' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/telephone' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/text' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/token' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => '8.x-1.7',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/token',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/toolbar' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/tour' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/tracker' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/twig_tweak' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'reference' => '8.x-2.6',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/twig_tweak',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/update' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/user' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/views' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/views_ui' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/workflows' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drupal/workspaces' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '8.8.6',
            ),
        ),
        'drush/drush' => array(
            'pretty_version' => '10.2.2',
            'version' => '10.2.2.0',
            'reference' => '8307a4e7dae9c63a279d8b59b9dca6c1973576c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drush/drush',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'easyrdf/easyrdf' => array(
            'pretty_version' => '0.9.1',
            'version' => '0.9.1.0',
            'reference' => 'acd09dfe0555fbcfa254291e433c45fdd4652566',
            'type' => 'library',
            'install_path' => __DIR__ . '/../easyrdf/easyrdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.17',
            'version' => '2.1.17.0',
            'reference' => 'ade6887fd9bd74177769645ab5c474824f8a418a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fabpot/goutte' => array(
            'pretty_version' => 'v3.2.3',
            'version' => '3.2.3.0',
            'reference' => '3f0eaf0a40181359470651f1565b3e07e3dd31b8',
            'type' => 'application',
            'install_path' => __DIR__ . '/../fabpot/goutte',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'grasmash/expander' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '95d6037344a4be1dd5f8e0b0b2571a28c397578f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/expander',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'grasmash/yaml-expander' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '3f0f6001ae707a24f4d9733958d77d92bf9693b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/yaml-expander',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.3',
            'version' => '6.5.3.0',
            'reference' => 'aab4ebd862aa7d04f01a4b51849d657db56d882e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'a59da6cf61d80060647ff4d3eb2c03a2bc694646',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '239400de7a173fe9901b9ac7c06497751f00727a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'instaclick/php-webdriver' => array(
            'pretty_version' => '1.4.7',
            'version' => '1.4.7.0',
            'reference' => 'b5f330e900e9b3edfc18024a5ec8c07136075712',
            'type' => 'library',
            'install_path' => __DIR__ . '/../instaclick/php-webdriver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'jcalderonzumba/gastonjs' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '575a9c18d8b87990c37252e8d9707b29f0a313f3',
            'type' => 'phantomjs-api',
            'install_path' => __DIR__ . '/../jcalderonzumba/gastonjs',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'jcalderonzumba/mink-phantomjs-driver' => array(
            'pretty_version' => 'v0.3.3',
            'version' => '0.3.3.0',
            'reference' => '008f43670e94acd39273d15add1e7348eb23848d',
            'type' => 'mink-driver',
            'install_path' => __DIR__ . '/../jcalderonzumba/mink-phantomjs-driver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'justinrainbow/json-schema' => array(
            'pretty_version' => '5.2.9',
            'version' => '5.2.9.0',
            'reference' => '44c6787311242a979fa15c704327c20e7221a0e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../justinrainbow/json-schema',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'league/container' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '43f35abd03a12977a60ffd7095efd6a7808488c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => '104443ad663d15981225f99532ba73c2f1d6b6f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikey179/vfsstream' => array(
            'pretty_version' => 'v1.6.8',
            'version' => '1.6.8.0',
            'reference' => '231c73783ebb7dd9ec77916c10037eff5a2b6efe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikey179/vfsstream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.9.5',
            'version' => '1.9.5.0',
            'reference' => 'b2c28789e80a97badd14145fda39b545d83ca3ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
            'replaced' => array(
                0 => '1.9.5',
            ),
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.4.0',
            'version' => '4.4.0.0',
            'reference' => 'bd43ec7152eaaab3bd8c6d0aa95ceeb1df8ee120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orno/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'pear/archive_tar' => array(
            'pretty_version' => '1.4.9',
            'version' => '1.4.9.0',
            'reference' => 'c5b00053770e1d72128252c62c2c1a12c26639f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/archive_tar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.10',
            'version' => '1.10.10.0',
            'reference' => '625a3c429d9b2c1546438679074cac1b089116a7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'dbb42a5a0e45f3adcf99babfb2a1ba77b8ac36a7',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '7761fcacf03b4d4f16e7ccb606d4879ca431fcf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '45a2ec53a73c70ce41d55cedef9063630abaf1b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '6568f4687e5b41b054365f9ae03fcb1ed5f2069b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.1.0',
            'version' => '5.1.0.0',
            'reference' => 'cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '7462d5f123dfc080dfdf26897032a6513644fc95',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => '4acfd6a4b33a509d8c88f50e5222f734b6aeebae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'reference' => '451c3cd1418cf640de218914901e51b064abb093',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '6.1.4',
            'version' => '6.1.4.0',
            'reference' => '807e6013b00af69b6c5d9ceb4282d0393dbb9d8d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '050bedf145a257b1ff02746c31894800e5122946',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'reference' => '1038454804406b0b5f5f520358e78c1c2f71501e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '995192df77f63a59e47f025390d2d1fdf8f425ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '7.5.20',
            'version' => '7.5.20.0',
            'reference' => '9467db479d1b0487c99733bb1e7944d32deded2c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
                1 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '0f73288fd15629204f9d42b7055f72dacbe811fc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.10.4',
            'version' => '0.10.4.0',
            'reference' => 'a8aec1b2981ab66882a01cce36a49b6317dc3560',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'roundcube/plugin-installer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.10',
            ),
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '5de4fc177adf9bce8df98d8d141a7559d7ccf6da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '720fcc7e9b5cf384ea68d9d930d480907a0c1a29',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '4.2.3',
            'version' => '4.2.3.0',
            'reference' => '464c90d7bdf5ad4e8a6aea15c091fec0603d4368',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '3.1.2',
            'version' => '3.1.2.0',
            'reference' => '68609e1261d215ea5b21b7987539cbfbe156ec3e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '7cfd9e65d11ffb5af41198476395774d4c8a84c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '773f97c67f28de00d397be301821b06708fca0be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '4d7a795d35b889bf80a0cc04e08d77cedfa917a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '99732be0ddb3361e16ad77b68ba41efc8e979019',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/jsonlint' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => 'ff2aa5420bfbc296cf6a0bc785fa5b35736de7c1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/jsonlint',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'seld/phar-utils' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '8800503d56b9867d43d9c303b9cbcc26016e82f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../seld/phar-utils',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'shama/baton' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.7.2',
            'version' => '3.7.2.0',
            'reference' => 'ed8e00df0a83aa96acf703f8c2979ff33341f879',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'stack/builder' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => 'a4faaa6f532c6086bc66c29e1bc6c29593e1ca7c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stack/builder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stecman/symfony-console-completion' => array(
            'pretty_version' => '0.11.0',
            'version' => '0.11.0.0',
            'reference' => 'a9502dab59405e275a9f264536c4e1cb61fc3518',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stecman/symfony-console-completion',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony-cmf/routing' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'reference' => 'fb1e7f85ff8c6866238b7e73a490a0a0243ae8ac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony-cmf/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '1c7bcd954ad1fc02354c4cfd3fcd1b0c95245367',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/class-loader' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'e4636a4f23f157278a19e5db160c63de0da297d8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/class-loader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '3634991bea549e73c45a964c38f30ceeae6ed877',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'bf60d5e606cd595391c5f82bf6b570d9573fa120',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '9ccf6e78077a3fc1596e6c7b5958008965a11518',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'ce9f3b5e8e1c50f849fded59b3a1b6bc3562ec29',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'd10ff5503b0b27711087eef4ac7835a752fe42fd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'ceacdab4abf7695ef6bec77c8b7983e1544c6358',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '9d4e22943b73acc1ba50595b7de1a01fe9dbad48',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '78a93e5606a19d0fb490afc3c4a9b7ecd86e1515',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'reference' => 'b6b6ad3db3edb1b4b1c1896b1975fb684994de6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'eded33daef1147be7ff1249706be9a49fe2c7a44',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '139d477cc926de9ca03c3d59b51ab6e22450c6df',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/lock' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'ce180b892bd7d6b0e10f662ca95f7c85350a62b0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/lock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/phpunit-bridge' => array(
            'pretty_version' => 'v3.4.39',
            'version' => '3.4.39.0',
            'reference' => 'c02893ae43532b46a4f0e0f207d088b939f278d9',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/phpunit-bridge',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'c4de7601eefbf25f9d47190abe07f79fe0a27424',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => '3bff59ea7047e925be6b7f2059d60af31bb46d6a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'fa79b11539418b02fc5e1897267673ba2c19419c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => '54b8cd7e6c1643d78d011f3be89f3ef1f9f4c675',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php70' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => '5f03a781d984aae42cebd18e7912fa80f02ee644',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.17.0',
            'version' => '1.17.0.0',
            'reference' => 'f048e612a3905f34931127360bdd2def19a5e582',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => 'f5104c9dcbc2cfad45d01d5150c1da9836967271',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '9ab9d71f97d5c7d35a121a7fb69f74fee95cd0ad',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '53b432fde8eea7dab820e75abda5b97fdaa829b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/serializer' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '2e1bdec403d8e7a350884cbbe4807ab7c2a843d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '4e844362f573713e6d45949795c95a4cb6cf760d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v3.4.40',
            'version' => '3.4.40.0',
            'reference' => '0d4d26bacafdead3b73586302fc5019efdfbdb2e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v4.4.8',
            'version' => '4.4.8.0',
            'reference' => 'c587e04ce5d1aa62d534a038f574d9a709e814cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'reference' => '88289caa3c166321883f67fe5130188ebbb47094',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => '11336f6f84e16a720dae9d8e6ed5019efa85a0f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v1.42.5',
            'version' => '1.42.5.0',
            'reference' => '87b2ea9d8f6fd014d0621ca089bb1b3769ea3f8e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typo3/phar-stream-wrapper' => array(
            'pretty_version' => 'v3.1.4',
            'version' => '3.1.4.0',
            'reference' => 'e0c1b495cfac064f4f5c4bcb6bf67bb7f345ed04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typo3/phar-stream-wrapper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v4.1.5',
            'version' => '4.1.5.0',
            'reference' => '539bb6927c101a5605d31d11a2d17185a2ce2bf1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webflo/drupal-finder' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '123e248e14ee8dd3fbe89fb5a733a6cf91f5820e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webflo/drupal-finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'reference' => 'ab2cb0b3b559010b75981b1bdce728da3ee90ad6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/path-util' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => 'd939f7edc24c9a1bb9c0dee5cb05d8e859490725',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/path-util',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zaporylie/composer-drupal-optimizations' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'a7f409a765164fd13ac0bd00e19109165c51b369',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../zaporylie/composer-drupal-optimizations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
